### ISSUE TITLE
Dataset?

### ISSUE THREAD

**Issue by divya200422** [conflick0/CardiacSeg#1]
Hello conflick0,
Which cardiac dataset is used ?
Thank you

**Comment by conflick0** [comment]
Hello divya200422,

The dataset is provided by the hospitals that collaborate with us, and we may not be able to provide it to you. However, here are some relevant open-source datasets that you can refer to:

https://paperswithcode.com/dataset/mm-whs-2017
https://paperswithcode.com/dataset/segthor

Regarding the code, we are developing based on MONAI. You can refer to the following links for more information:

Documentation: https://docs.monai.io/en/stable/
Tutorials: https://github.com/Project-MONAI/tutorials/blob/main/3d_segmentation/spleen_segmentation_3d.ipynb

Thank you.

**Comment by divya200422** [comment]
Thank you
